name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      # Install Gyan full ffmpeg via winget
      - name: Install ffmpeg (Gyan full) via winget
        run: |
          winget install --id=Gyan.FFmpeg -e --accept-package-agreements --accept-source-agreements

      - name: Locate ffmpeg.exe
        shell: pwsh
        run: |
          $real = Get-ChildItem 'C:\Program Files\ffmpeg\bin' -Filter ffmpeg.exe -Recurse | Select-Object -First 1 -ExpandProperty FullName
          if (-not $real) { throw "ffmpeg.exe not found after winget install" }
          "FFMPEG_EXE=$real" | Out-File -FilePath $Env:GITHUB_ENV -Append
          Write-Host "Using ffmpeg at $real"

      - name: Build one-file exe
        shell: pwsh
        run: |
          pyinstaller --name FFmpegCompressor --onefile --noconsole gui_ffmpeg_compressor.py --add-binary "$Env:FFMPEG_EXE;."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFmpegCompressor-Windows
          path: dist/FFmpegCompressor.exe
