name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      # Download Gyan full build
      - name: Download ffmpeg (Gyan full static build)
        shell: pwsh
        run: |
          $url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z"
          $out = "ffmpeg.7z"
          Invoke-WebRequest -Uri $url -OutFile $out
          # Extract with 7zip (preinstalled on GitHub runner)
          7z x $out -y -offmpeg
          $real = Get-ChildItem "ffmpeg" -Recurse -Filter ffmpeg.exe | Select-Object -First 1 -ExpandProperty FullName
          if (-not $real) { throw "ffmpeg.exe not found after download" }
          "FFMPEG_EXE=$real" | Out-File -FilePath $Env:GITHUB_ENV -Append
          Write-Host "Using ffmpeg at $real"

      - name: Build one-file exe
        shell: pwsh
        run: |
          pyinstaller --name FFmpegCompressor --onefile --noconsole gui_ffmpeg_compressor.py --add-binary "$Env:FFMPEG_EXE;."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFmpegCompressor-Windows
          path: dist/FFmpegCompressor.exe
